### PR TITLE
Add directory for tutoring on Wednesday + Add Rainbow to LED ring

### PR DESCRIPTION
**Pull request by creaturekaspar**
This is where I'll be tutoring new members on Java basics.

### CODE REVIEW

**Comment by kasemir** [comment]
Well, we can't do this on the actual robot:
```
public void execute()
{
    for (int i = 0; i < 256; i++)
    {
        ...
        Thread.sleep(3);
    }
    for (int i = 0; i < 256; i++)
    {
        ...
        Thread.sleep(3);
    }
    ...
```
This will sleep for multiples of 256*3 ms, overall more than a second.
All we do in one call to `execute` must complete in way less than 20ms, otherwise everything else gets delayed, the robot would drive intermittently.

See WPILib examples, https://docs.wpilib.org/en/latest/docs/software/examples-tutorials/wpilib-examples.html, specifically 
https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/addressableled/Robot.java
for one way to do a basic rainbow, where the key idea is this:
Some `int m_rainbowFirstPixelHue` gets incremented on each call, i.e., at 50 Hz.
From that, the color is then set for that run of `robotPeriodic` (the equivalent of `execute` for a command).

**Comment by kasemir** [comment]
I've added your wednesdaytutoring/Main.java, that's a good idea to start adding files there

**Comment by creaturekaspar** [comment]
I believe I fixed the issue you were describing with Rainbow.java in the above commit.

**Comment by kasemir** [comment]
Yes, no more `sleep`, very good!

That `stage` to track what you want to do over time is the right idea.
Sometimes you can use something like
```
stage = (current_time_in_seconds / time_per_stage) % number_of_stages;
```

In other cases, you move to the next stage based on some other criterion, like in your example when that counter `i` reaches 255.

**Pull request merged**
